### ISSUE TITLE
This doesn't work on Android 6.0.0 with ti5.4.0

### ISSUE THREAD

**Issue by e-m-s-y** [ricardoalcocer/AndroidRotateImage#3]
Took the picture in portrait mode, previewer shows image rotated, i click the check / approve icon and the image returned is in landscape.

Logs:
[INFO] :   I/com.company.utils: (main) [1,8247] In rotateResizeImage
[INFO] :   I/com.company.utils: (main) [0,8247] Detected orientation: 0
[INFO] :   I/com.company.utils: (main) [0,8247] Determined rotation: 0
[INFO] :   I/com.company.utils: (main) [0,8247] Original image size: 480x480
[INFO] :   I/com.company.utils: (main) [0,8247] Sample size: 1
[INFO] :   I/com.company.utils: (main) [3,8250] Sampled image size: 480x480
[INFO] :   I/com.company.utils: (main) [4,8254] Scaled image size: 640x640
[INFO] :   I/com.company.utils: (main) [0,8254] Deleted old file
[INFO] :   I/com.company.utils: (main) [0,8254] Created new file
[INFO] :   I/com.company.utils: (main) [10,8264] Copied rotated, resized image to new file

Tested on a Google Nexus 5 (1080x1920)

**Comment by ricardoalcocer** [comment]
I just merged a fix.  Could you confirm it works?

**Comment by ricardoalcocer** [comment]
Hey Tim @skypanther .  I believe you worked on this.  Could you confirm this actually works so I can close this issue?

**Comment by skypanther** [comment]
Hi @ricardoalcocer I'm using this module with Ti 6.0.2.GA without problems. The PR of mine you just merged was to add Ti 6 support. However, before that, you merged my previous PR which added Android 6 support with the Ti 5.x branch. We certainly used the module back then. 

Keep in mind that not all Android devices record the exif data in the image. I believe your module relies on the exif data to determine the initial rotation. Some devices record that info in the cameraInfo block instead. The Nexus 5 is one of those devices. (In fact, I have this same issue with my [Android image rotation module](https://github.com/skypanther/TiRotate/issues/1).)

**Comment by ricardoalcocer** [comment]
Yeah you're right @skypanther , it relies on EXIF.  I'll close this for now.  Thanks!
