### ISSUE TITLE
Does not work with Ti 6.0.0.GA

### ISSUE THREAD

**Issue by ghost** [ricardoalcocer/AndroidRotateImage#7]
Hi,

I am trying to add this module in my project but it does not load. I have Ti 6.0.0.GA and this imageutility supports Ti 6.0.0.v2 which is not available in Axway Appcelerator Studio SDK release list. I have attached the sdk list screen shot for reference. 

Any assistance will be appreciated.

Many thanks.

![screen shot 2018-01-11 at 12 45 13 pm](https://user-images.githubusercontent.com/13151104/34812836-77e14b44-f6cd-11e7-892d-c5a2b9cd8911.png)

**Comment by ricardoalcocer** [comment]
Closing this tix.  The code was updated but is pending compilation.
